apiVersion: v1
kind: Service
metadata:
  labels:
    name: webfront
  name: webfront
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  selector:
    name: webfront
  type: LoadBalancer
  loadBalancerIP: <IP OF THE LOADBALANCER>
